#!/bin/sh
set -ex

git submodule update --init

cd .io

mkdir -p i && cd i

python -m venv python && source python/bin/activate
pip install adafruit-nrfutil
pip install -r ../../tools/mcuboot/requirements.txt

( set -e

	i() { (
		[ -d "$1" ] || {
			curl -o tmp "$2"
			unzip tmp -d "$1" 2>/dev/null || { mkdir -p "$1" && tar -xvf tmp -C "$1"; }
		}
		rm -f tmp; ) }
	i nRF5 'https://nsscprodmedia.blob.core.windows.net/prod/software-and-other-downloads/sdks/nrf5/binaries/nrf5_sdk_17.1.0_ddde560.zip'
	i arm-none-eabi 'https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/10.3-2021.10/gcc-arm-none-eabi-10.3-2021.10-x86_64-linux.tar.bz2'
)

cd ..

i() { (
	i="$(cat "$1" || echo 0)"
	echo "$((i + 1))" > "$1"
	echo "$i"; ) }

VERSION="2.10.$(i i/buildnum)"

mkdir -p o/build && cd o/build

cmake \
	-DARM_NONE_EABI_TOOLCHAIN_PATH="$(realpath ../../i/arm-none-eabi/gcc-arm-none-eabi-10.3-2021.10)" \
	-DNRF5_SDK_PATH="$(realpath ../../i/nRF5/nRF5_SDK_17.1.0_ddde560)" \
	-DBUILD_DFU=1 \
	-DPROJECT_VERSION="$VERSION" \
	-DENABLE_WATCHFACES='WatchFace::Digital,WatchFace::Custom,WatchFace::Analog' \
	-S ../../..

make -j8 pinetime-mcuboot-app

cd ..

cp build/src/pinetime-mcuboot-app-dfu-"$VERSION".zip pinetime-mcuboot-app-dfu.zip
