#!/bin/sh
set -eu

(
	cd src/displayapp/fonts
	for i in Bold ExtraBold Light Regular; do
		ln -vsf "$(fc-match "sans-serif:$i" -f '%{file}')" "JetBrainsMono-$i.ttf"
	done
)

cd .io
rm -rf o
mkdir -p o/build

i="$(cat i/buildnum || echo 0)"

(
	cd o/build

	cmake \
		-DARM_NONE_EABI_TOOLCHAIN_PATH="$ARM_NONE_EABI_TOOLCHAIN_PATH" \
		-DNRF5_SDK_PATH="$NRF5_SDK_PATH" \
		-DBUILD_DFU=1 \
		-DPROJECT_VERSION="2.10.$i" \
		-DENABLE_WATCHFACES='WatchFace::Digital,WatchFace::Custom,WatchFace::Analog' \
		-S ../../..

	exec make -j8 pinetime-mcuboot-app
)

echo $((i + 1)) >i/buildnum
