#!/bin/sh
set -eu

cd .io

[ -d sim ] || git clone --depth 1 --recursive 'https://github.com/InfiniTimeOrg/InfiniSim' sim

cd sim

cmake \
	-DInfiniTime_DIR=../.. \
	-DBUILD_RESOURCES=OFF \
	-DWITH_PNG=OFF \
	-DPROJECT_VERSION="2.10.$(cat ../i/buildnum)" \
	-S . -B build

cmake --build build -j4

exec build/infinisim --hide-status
