#!/bin/sh
set -e

mkdir -p .io/i && cd .io/i

[ -d sim ] || git clone --depth 1 --recursive 'https://github.com/InfiniTimeOrg/InfiniSim' sim

python -m venv python && source python/bin/activate
pip install wheel Pillow

cd sim

cmake \
	-DInfiniTime_DIR=../../.. \
	-DBUILD_RESOURCES=OFF \
	-DWITH_PNG=OFF \
	-DPROJECT_VERSION="2.10.$(cat ../buildnum)" \
	-S . -B build

cmake --build build -j4

build/infinisim --hide-status
